name: Track Bluesky Followers

on:
  schedule:
    - cron: '0 0 1 * *'      # runs monthly on the 1st at 00:00 UTC
  workflow_dispatch:         # (optional) lets you run it manually too

jobs:
  track:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install playwright
          playwright install chromium

      - name: Run follower scraper
        run: python bluesky_followers/monthly.py

      - name: Commit updated CSV
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add -f bluesky_followers/data/bsky_followers.csv
          git commit -m "Monthly update: $(date +'%Y-%m-%d')" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GH_PAT }}@github.com/${{ github.repository }} HEAD:${{ github.ref }}

    
