name: Track Bluesky Followers

on:
  schedule:
    - cron: '0 0 1 * *'  # monthly
  workflow_dispatch:

jobs:
  track:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev libssl-dev libxml2-dev

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install R packages
        run: |
          install.packages("bskyr", repos = c("https://christopherkenny.r-universe.dev", "https://cloud.r-project.org"))
        shell: Rscript {0}

      - name: Run follower scraper
        run: Rscript bluesky_followers/monthly.R

      - name: Commit updated CSV
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add -f bluesky_followers/data/bsky_followers.csv
          git commit -m "Monthly update: $(date +'%Y-%m-%d')" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GH_PAT }}@github.com/${{ github.repository }} HEAD:${{ github.ref }}
