name: Track Instagram Followers

on:
  schedule:
    - cron: '0 12 1 * *'  # Runs monthly, on the 1st at 12:00 UTC
  workflow_dispatch:

jobs:
  track:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: pip install requests
      - name: Run script
        run: python instagram_monthly.py
      - name: Commit and push CSV
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add followers_log.csv
          git commit -m "Update follower count" || echo "No changes to commit"
          git push
